fps = True
fullscreen = True
gravity = 10
position_iterations = 10
velocity_iterations = 10
icarus_lift_force = 15
icarus_side_force = 5
icarus_air_resistance = 1
icarus_angular_k = 10
icarus_angular_damping = 2
heat_duration = 5
burn_duration = 5
cool_duration = 10
flight_duration = 20
rest_duration = 5
sky_color = 0.7, 0.8, 0.9
shadow_color = 0.6, 0.7, 0.8
cloud_height = 1
